server:
  port: 8080

# spring datasource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33001/scenario
    username: root
    password: 12345
    hikari:
      pool-name: hikari-mysql
      auto-commit: false
      connection-timeout: 5000
      minimum-idle: 5
      #idle-timeout: ''

# mybatis
# http://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/
mybatis:
  type-aliases-package: per.itachi.scenario.db2j.entity.db
  mapper-locations: mapper/mysql/*Mapper.xml

# biz strategy
db:
  id-gen:
    snowflake:
      count-of-bits:
        timestamp: 41
        db-nbr: 5
        table-nbr: 5
        sequence: 12
      sequence:
        step-size: 10
        log-count-of-retry-threshold: 10
