-- T_SEQ_INCREMENT
create table T_SEQ_INCREMENT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	TABLE_NAME VARCHAR(60) NOT NULL,
	TABLE_NBR INT NOT NULL,
	COLUMN_NAME VARCHAR(60) NOT NULL,
	CURRENT_POS INT NOT NULL,
	STEP_SIZE INT NOT NULL,
	VERSION INT NOT NULL,
	CDATE DATETIME NOT NULL,
	EDATE DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_SEQ_INCREMENT_TABLE_NBR_COL ON T_SEQ_INCREMENT(TABLE_NAME, TABLE_NBR, COLUMN_NAME);

-- DROP TABLE T_SEQ_INCREMENT;