-- T_SEQ_INCREMENT
create table T_SEQ_INCREMENT (
	ID BIGINT,
	TABLE_NAME VARCHAR(60),
	TABLE_NBR INT,
	COLUMN_NAME VARCHAR(60),
	CURRENT_POS INT,
	STEP_SIZE INT,
	VERSION INT,
	CDATE DATETIME,
	EDATE DATETIME,
	PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX UK_SEQ_INCREMENT_TABLE_NBR_COL ON T_SEQ_INCREMENT(TABLE_NAME, TABLE_NBR, COLUMN_NAME);

